# Generated by Django 2.0.2 on 2018-02-23 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kudos.models


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='kudo given date')),
            ],
        ),
        migrations.CreateModel(
            name='KudoTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kudo_title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='release start date')),
                ('end_date', models.DateTimeField(verbose_name='release end date')),
                ('is_current_release', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', kudos.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='kudo',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grantor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kudo',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudos.Release'),
        ),
        migrations.AddField(
            model_name='kudo',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudos.KudoTitle'),
        ),
        migrations.AddField(
            model_name='kudo',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kudos.Team'),
        ),
    ]
